import { Employee, VacationRequest, Candidate, DocumentItem, TimeRecord } from '@/lib/types/database.types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    organization_id: 'org-vortex',
    full_name: 'Lucas Gomes',
    email: 'lucas.gomes@vortex.pt',
    phone: '+351 912 345 678',
    nif: '245678910',
    niss: '12034567891',
    role_title: 'Engenheiro Fullstack Sénior',
    department: 'Tecnologia',
    admission_date: '2024-01-10',
    salary: 2850,
    vacation_balance_days: 18,
    status: 'active',
    avatar_color: 'bg-nexu-coral',
  },
  {
    id: 'emp-2',
    organization_id: 'org-vortex',
    full_name: 'Mariana Santos',
    email: 'mariana.santos@vortex.pt',
    phone: '+351 913 456 789',
    nif: '256789012',
    niss: '12145678902',
    role_title: 'Design Lead & UX',
    department: 'Design',
    admission_date: '2023-03-15',
    salary: 2400,
    vacation_balance_days: 22,
    status: 'active',
    avatar_color: 'bg-nexu-indigo',
  },
  {
    id: 'emp-3',
    organization_id: 'org-vortex',
    full_name: 'Ana Ferreira',
    email: 'ana.ferreira@vortex.pt',
    phone: '+351 914 567 890',
    nif: '267890123',
    niss: '12256789013',
    role_title: 'Product Manager',
    department: 'Produto',
    admission_date: '2024-06-01',
    salary: 2600,
    vacation_balance_days: 14,
    status: 'active',
    avatar_color: 'bg-emerald-600',
  },
  {
    id: 'emp-4',
    organization_id: 'org-vortex',
    full_name: 'Rafael Lima',
    email: 'rafael.lima@vortex.pt',
    phone: '+351 915 678 901',
    nif: '278901234',
    niss: '12367890124',
    role_title: 'Engenheiro Backend',
    department: 'Tecnologia',
    admission_date: '2024-08-12',
    salary: 2200,
    vacation_balance_days: 11,
    status: 'active',
    avatar_color: 'bg-amber-600',
  },
  {
    id: 'emp-5',
    organization_id: 'org-vortex',
    full_name: 'Beatriz Costa',
    email: 'beatriz.costa@vortex.pt',
    phone: '+351 916 789 012',
    nif: '289012345',
    niss: '12478901235',
    role_title: 'Especialista em Gestão LT e Pessoal',
    department: 'Gestão LT',
    admission_date: '2023-02-20',
    salary: 1950,
    vacation_balance_days: 16,
    status: 'active',
    avatar_color: 'bg-purple-600',
  },
  {
    id: 'emp-6',
    organization_id: 'org-vortex',
    full_name: 'Carlos Eduardo Silva',
    email: 'carlos.eduardo@vortex.pt',
    phone: '+351 917 890 123',
    nif: '290123456',
    niss: '12589012346',
    role_title: 'Executivo de Contas B2B',
    department: 'Comercial',
    admission_date: '2024-05-05',
    salary: 1800,
    vacation_balance_days: 10,
    status: 'active',
    avatar_color: 'bg-blue-600',
  },
  {
    id: 'emp-7',
    organization_id: 'org-vortex',
    full_name: 'Juliana Pires',
    email: 'juliana.pires@vortex.pt',
    phone: '+351 918 901 234',
    nif: '231234567',
    niss: '12690123457',
    role_title: 'Investigadora UX (UX Researcher)',
    department: 'Design',
    admission_date: '2024-11-18',
    salary: 1900,
    vacation_balance_days: 7,
    status: 'active',
    avatar_color: 'bg-rose-500',
  },
  {
    id: 'emp-8',
    organization_id: 'org-vortex',
    full_name: 'Tiago Martins',
    email: 'tiago.martins@vortex.pt',
    phone: '+351 919 012 345',
    nif: '242345678',
    niss: '12701234568',
    role_title: 'Engenheiro Frontend',
    department: 'Tecnologia',
    admission_date: '2025-02-01',
    salary: 2150,
    vacation_balance_days: 5,
    status: 'active',
    avatar_color: 'bg-teal-600',
  },
];

export const INITIAL_VACATIONS: VacationRequest[] = [
  {
    id: 'vac-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-2',
    employee_name: 'Mariana Santos',
    employee_role: 'Design Lead & UX',
    start_date: '2026-09-15',
    end_date: '2026-09-25',
    days_count: 9,
    vacation_type: 'regular_vacation',
    status: 'pending',
    reason: 'Férias de verão previstas no mapa de férias anual (Código do Trabalho Art. 241º)',
  },
  {
    id: 'vac-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    employee_name: 'Lucas Gomes',
    employee_role: 'Engenheiro Fullstack Sénior',
    start_date: '2026-10-01',
    end_date: '2026-10-03',
    days_count: 3,
    vacation_type: 'day_off',
    status: 'pending',
    reason: 'Compensação de horas extraordinárias em projeto crítico',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    organization_id: 'org-vortex',
    full_name: 'Diogo Ramos',
    email: 'diogo.ramos@email.pt',
    role_applied: 'Engenheiro React / Next.js Sénior',
    stage: 'triagem',
    fit_score: 94,
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind'],
  },
  {
    id: 'cand-2',
    organization_id: 'org-vortex',
    full_name: 'Francisca Lima',
    email: 'francisca.lima@email.pt',
    role_applied: 'Product Designer',
    stage: 'triagem',
    fit_score: 89,
    tags: ['Figma', 'Design System', 'User Testing'],
  },
  {
    id: 'cand-3',
    organization_id: 'org-vortex',
    full_name: 'Gabriel Torres',
    email: 'gabriel.torres@email.pt',
    role_applied: 'Especialista DevOps & Cloud',
    stage: 'entrevista',
    fit_score: 95,
    tags: ['AWS', 'Kubernetes', 'CI/CD', 'Terraform'],
  },
  {
    id: 'cand-4',
    organization_id: 'org-vortex',
    full_name: 'Inês Alencar',
    email: 'ines.alencar@email.pt',
    role_applied: 'Técnica de Gestão LT e Processamento Salarial',
    stage: 'proposta',
    fit_score: 98,
    tags: ['Código do Trabalho', 'Registo ACT', 'Segurança Social Direta', 'IRS'],
  },
  {
    id: 'cand-5',
    organization_id: 'org-vortex',
    full_name: 'Vasco Meireles',
    email: 'vasco.meireles@email.pt',
    role_applied: 'Gestor de Contas B2B (SaaS)',
    stage: 'contratado',
    fit_score: 96,
    tags: ['SaaS B2B', 'HubSpot', 'Vendas Corporativas'],
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    employee_name: 'Lucas Gomes',
    title: 'Contrato_Trabalho_SemTermo_LucasGomes.pdf',
    file_url: 'https://storage.nexuslt.pt/docs/contrato_lucas.pdf',
    doc_type: 'contrato',
    status: 'signed',
    signed_at: '2026-08-10T14:30:00Z',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'doc-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-3',
    employee_name: 'Ana Ferreira',
    title: 'Acordo_Confidencialidade_Equipamento_Ana.pdf',
    file_url: 'https://storage.nexuslt.pt/docs/acordo_ana.pdf',
    doc_type: 'termo',
    status: 'pending',
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'doc-3',
    organization_id: 'org-vortex',
    employee_name: 'Todos os Colaboradores (8)',
    title: 'Recibos_Vencimento_Agosto2026_Assinados.pdf',
    file_url: 'https://storage.nexuslt.pt/docs/recibos_ago2026.pdf',
    doc_type: 'recibo_vencimento',
    status: 'signed',
    signed_at: '2026-09-05T09:00:00Z',
    created_at: '2026-09-05T08:00:00Z',
  },
];

export const INITIAL_TIME_RECORDS: TimeRecord[] = [
  {
    id: 'time-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    punch_time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'Porto, Portugal (App Móvel com Geovalidação)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-2',
    punch_time: new Date(Date.now() - 3.8 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'Matosinhos, Porto (Reconhecimento Facial)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-3',
    organization_id: 'org-vortex',
    employee_id: 'emp-3',
    punch_time: new Date(Date.now() - 3.7 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'Vila Nova de Gaia, Porto (Portal Web)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-4',
    organization_id: 'org-vortex',
    employee_id: 'emp-6',
    punch_time: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'Porto, Portugal (App Móvel com Geovalidação)',
    created_at: new Date().toISOString(),
  },
];
