import { Employee, VacationRequest, Candidate, DocumentItem, TimeRecord } from '@/lib/types/database.types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    organization_id: 'org-vortex',
    full_name: 'Lucas Gomes',
    email: 'lucas.gomes@vortex.com',
    phone: '(11) 98765-4321',
    role_title: 'Engenheiro Fullstack Senior',
    department: 'Tecnologia',
    admission_date: '2024-01-10',
    salary: 14500,
    vacation_balance_days: 18,
    status: 'active',
    avatar_color: 'bg-nexu-coral',
  },
  {
    id: 'emp-2',
    organization_id: 'org-vortex',
    full_name: 'Mariana Santos',
    email: 'mariana.santos@vortex.com',
    phone: '(11) 98765-1234',
    role_title: 'Design Lead & UX',
    department: 'Design',
    admission_date: '2023-03-15',
    salary: 12800,
    vacation_balance_days: 22,
    status: 'active',
    avatar_color: 'bg-nexu-indigo',
  },
  {
    id: 'emp-3',
    organization_id: 'org-vortex',
    full_name: 'Ana Ferreira',
    email: 'ana.ferreira@vortex.com',
    phone: '(11) 97654-3210',
    role_title: 'Product Manager',
    department: 'Produto',
    admission_date: '2024-06-01',
    salary: 13500,
    vacation_balance_days: 12,
    status: 'active',
    avatar_color: 'bg-emerald-600',
  },
  {
    id: 'emp-4',
    organization_id: 'org-vortex',
    full_name: 'Rafael Lima',
    email: 'rafael.lima@vortex.com',
    phone: '(11) 96543-2109',
    role_title: 'Backend Developer',
    department: 'Tecnologia',
    admission_date: '2024-08-12',
    salary: 10500,
    vacation_balance_days: 8,
    status: 'active',
    avatar_color: 'bg-amber-600',
  },
  {
    id: 'emp-5',
    organization_id: 'org-vortex',
    full_name: 'Beatriz Costa',
    email: 'beatriz.costa@vortex.com',
    phone: '(11) 95432-1098',
    role_title: 'Especialista em DP & RH',
    department: 'RH & DP',
    admission_date: '2023-02-20',
    salary: 9200,
    vacation_balance_days: 15,
    status: 'active',
    avatar_color: 'bg-purple-600',
  },
  {
    id: 'emp-6',
    organization_id: 'org-vortex',
    full_name: 'Carlos Eduardo',
    email: 'carlos.eduardo@vortex.com',
    phone: '(11) 94321-0987',
    role_title: 'Executivo de Contas B2B',
    department: 'Vendas',
    admission_date: '2024-05-05',
    salary: 8500,
    vacation_balance_days: 10,
    status: 'active',
    avatar_color: 'bg-blue-600',
  },
  {
    id: 'emp-7',
    organization_id: 'org-vortex',
    full_name: 'Juliana Paes',
    email: 'juliana.paes@vortex.com',
    phone: '(11) 93210-9876',
    role_title: 'UX Researcher',
    department: 'Design',
    admission_date: '2024-11-18',
    salary: 9800,
    vacation_balance_days: 5,
    status: 'active',
    avatar_color: 'bg-rose-500',
  },
  {
    id: 'emp-8',
    organization_id: 'org-vortex',
    full_name: 'Thiago Martins',
    email: 'thiago.martins@vortex.com',
    phone: '(11) 92109-8765',
    role_title: 'Frontend Engineer',
    department: 'Tecnologia',
    admission_date: '2025-02-01',
    salary: 11000,
    vacation_balance_days: 3,
    status: 'active',
    avatar_color: 'bg-teal-600',
  },
];

export const INITIAL_VACATIONS: VacationRequest[] = [
  {
    id: 'vac-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-2',
    employee_name: 'Mariana Santos',
    employee_role: 'Design Lead',
    start_date: '2026-09-15',
    end_date: '2026-09-25',
    days_count: 10,
    vacation_type: 'regular_vacation',
    status: 'pending',
    reason: 'Férias regulares período 2024/2025',
  },
  {
    id: 'vac-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    employee_name: 'Lucas Gomes',
    employee_role: 'Engenheiro Fullstack',
    start_date: '2026-10-01',
    end_date: '2026-10-05',
    days_count: 5,
    vacation_type: 'day_off',
    status: 'pending',
    reason: 'Folga compensatória de banco de horas',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    organization_id: 'org-vortex',
    full_name: 'Diego Ramos',
    email: 'diego.ramos@email.com',
    role_applied: 'Senior React / Next.js Developer',
    stage: 'triagem',
    fit_score: 92,
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind'],
  },
  {
    id: 'cand-2',
    organization_id: 'org-vortex',
    full_name: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    role_applied: 'Product Designer',
    stage: 'triagem',
    fit_score: 88,
    tags: ['Figma', 'Design System', 'User Testing'],
  },
  {
    id: 'cand-3',
    organization_id: 'org-vortex',
    full_name: 'Gabriel Torres',
    email: 'gabriel.torres@email.com',
    role_applied: 'DevOps & Cloud Specialist',
    stage: 'entrevista',
    fit_score: 95,
    tags: ['AWS', 'Kubernetes', 'CI/CD', 'Terraform'],
  },
  {
    id: 'cand-4',
    organization_id: 'org-vortex',
    full_name: 'Larissa Alencar',
    email: 'larissa.alencar@email.com',
    role_applied: 'Coordenadora de DP & RH',
    stage: 'proposta',
    fit_score: 98,
    tags: ['eSocial', 'Portaria 671', 'Gestão de Folha'],
  },
  {
    id: 'cand-5',
    organization_id: 'org-vortex',
    full_name: 'Victor Meirelles',
    email: 'victor.meirelles@email.com',
    role_applied: 'Account Executive B2B',
    stage: 'contratado',
    fit_score: 96,
    tags: ['SaaS B2B', 'HubSpot', 'Inside Sales'],
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    employee_name: 'Lucas Gomes',
    title: 'Contrato_Trabalho_LucasGomes_CLT.pdf',
    file_url: 'https://storage.nexuhr.com/docs/contrato_lucas.pdf',
    doc_type: 'contrato',
    status: 'signed',
    signed_at: '2026-08-10T14:30:00Z',
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'doc-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-3',
    employee_name: 'Ana Ferreira',
    title: 'Termo_Confidencialidade_Equipamento_Ana.pdf',
    file_url: 'https://storage.nexuhr.com/docs/termo_ana.pdf',
    doc_type: 'termo',
    status: 'pending',
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'doc-3',
    organization_id: 'org-vortex',
    employee_name: 'Todos os Colaboradores (8)',
    title: 'Holerite_Consolidado_Agosto2026.pdf',
    file_url: 'https://storage.nexuhr.com/docs/holerite_ago2026.pdf',
    doc_type: 'holerite',
    status: 'signed',
    signed_at: '2026-09-05T09:00:00Z',
    created_at: '2026-09-05T08:00:00Z',
  },
];

export const INITIAL_TIME_RECORDS: TimeRecord[] = [
  {
    id: 'time-1',
    organization_id: 'org-vortex',
    employee_id: 'emp-1',
    punch_time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'São Paulo, SP (App Mobile GPS)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-2',
    organization_id: 'org-vortex',
    employee_id: 'emp-2',
    punch_time: new Date(Date.now() - 3.8 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'São Paulo, SP (Reconhecimento Facial)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-3',
    organization_id: 'org-vortex',
    employee_id: 'emp-3',
    punch_time: new Date(Date.now() - 3.7 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'São Paulo, SP (Portal Web)',
    created_at: new Date().toISOString(),
  },
  {
    id: 'time-4',
    organization_id: 'org-vortex',
    employee_id: 'emp-6',
    punch_time: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    punch_type: 'entry',
    location_name: 'São Paulo, SP (App Mobile GPS)',
    created_at: new Date().toISOString(),
  },
];
